import Layout from "../../components/layout";
import Head from "next/head";
import Image from "next/image";
import {useState} from "react";
import {Star} from "../../components/star";

export default function Login() {
    const [hidePassword, setHidePassword] = useState(true);

    function onHidePassword() {
        setHidePassword(!hidePassword);
    }

    return (
        <Layout>
            <Head>
                <title>Sloby Login</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                {Array.from({ length: 20 }, (_, i) => <Star key={i}/>)}
                <div className={"flex-center flex-col gap-8 lg:p-40"}>
                    <div className={"flex flex-row bg-dark-dark rounded-lg w-2/3 z-50"}>
                        <div className={"bg-dark-mid flex-center rounded-l-lg w-1/2"}>
                            <Image alt="Sloby Logo" src={"/images/Sloby Logo Dark.svg"} width={400} height={500}/>
                        </div>
                        <div className={"w-1/2 flex flex-col justify-between m-16 gap-8"}>
                            <p className={"font-semibold text-5xl"}>Log In</p>
                            <label className="block flex flex-col gap-2">
                                <span className="">Your email</span>
                                <input type="text"
                                       className="px-6 rounded-full mt-1 block w-full rounded-md bg-dark-mid border-transparent focus:border-gray-500 focus:bg-dark-dark focus:ring-0"
                                       placeholder="Enter your email"/>
                            </label>
                            <label className="block flex flex-col gap-2">
                                <span className="">Your password</span>
                                <input type={hidePassword ? "password" : "text"}
                                       className="px-6 rounded-full mt-1 block w-full rounded-md bg-dark-mid border-transparent focus:border-gray-500 focus:bg-dark-dark focus:ring-0"
                                       placeholder="Enter your password"></input>
                                <label className="mt-2 inline-flex items-center">
                                    <input type="checkbox"
                                           onClick={onHidePassword}
                                           className="rounded bg-gray-200 border-transparent focus:border-transparent focus:bg-dark-mid text-gray-700 focus:ring-1 focus:ring-offset-2 focus:ring-gray-500"/>
                                    <span className="ml-2">Show password</span>
                                </label>
                            </label>
                            <div className={"flex flex-col gap-3"}>
                                <div className={"flex-center bg-green-dark w-1/4 p-3 rounded-full"}>
                                    <p>Submit</p>
                                </div>
                                <p>Not a member? Sign up</p>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </Layout>
    )
}
